# Generated by Django 4.2 on 2023-04-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logTracker', '0002_membershistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logTracker.member')),
            ],
        ),
    ]
